from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
import uuid

from app.schemas.matching import CandidateProfile

class ApplicationRequest(BaseModel):
    """
    Request payload to initiate CV tailoring and cover letter generation.
    """
    candidate_id: uuid.UUID = Field(..., description="Unique identifier of the candidate")
    job_id: uuid.UUID = Field(..., description="Unique identifier of the target job")
    candidate_profile: CandidateProfile = Field(..., description="Candidate's current profile")
    job_description: Optional[str] = Field(None, description="Full text of the target job description. If not provided, it will be resolved from the JobRepository using job_id.")

class CVTailoringResult(BaseModel):
    """
    Structured output for CV tailoring suggestions.
    
    WARNING: Content is AI-generated and may contain hallucinated or incorrect 
    suggestions. A human must verify that these suggestions do not misrepresent 
    the candidate's actual skills.
    """
    tailored_summary: str = Field(..., description="A customized professional summary highlighting relevant experience for the target job")
    highlighted_skills: List[str] = Field(default_factory=list, description="List of the candidate's existing skills most relevant to the target job")
    missing_skills: List[str] = Field(default_factory=list, description="Skills mentioned in the job description that the candidate appears to lack")
    bullet_point_suggestions: List[str] = Field(default_factory=list, description="Suggestions for rephrasing experience bullet points to better align with the job requirements")

class CoverLetterResult(BaseModel):
    """
    Structured output for the generated cover letter.
    
    WARNING: The draft content is generated by an LLM and is considered an initial 
    draft only. Human review is mandatory to ensure factual accuracy and appropriate tone.
    """
    draft_content: str = Field(..., description="The complete text of the generated cover letter draft")
    tone_analysis: str = Field(..., description="Brief explanation of the tone used in the cover letter (e.g., formal, enthusiastic, professional)")

class ApplicationResponse(BaseModel):
    """
    The final combined response returned to the client.
    
    WARNING: Contains AI-generated application materials. A mandatory human-in-the-loop 
    review process must be completed before submitting these materials to an employer.
    """
    candidate_id: uuid.UUID
    job_id: uuid.UUID
    cv_tailoring: CVTailoringResult
    cover_letter: CoverLetterResult
    status: str = Field(default="Draft - Awaiting Human Approval", description="Status of the generated content indicating it requires human review.")
    disclaimer: str = Field(default="AI-generated content. A human-in-the-loop review is required before use.", description="Responsible AI disclaimer regarding potential hallucinations.")
